// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://veucnlwwupyeldsfhzlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZldWNubHd3dXB5ZWxkc2Zoemx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzMyODYsImV4cCI6MjA1ODgwOTI4Nn0.kIF8Db3WjI37ceKfJtSc8Ip3GHbkpsDlWQE24_dC9zY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);